#define GREY		RGB  0.5  0.5  0.5
#define BLACK       RGB  0    0    0
#define WHITE		RGB  1    1    1

#define RED         RGB  1    0    0
#define GREEN		RGB  0    1    0
#define BLUE		RGB  0    0    1
#define CYAN		RGB  0    1    1
#define YELLOW		RGB  1    1    0
#define MAGENTA		RGB  1    0    1

#define PINK		RGB  1    0.8  0.8
#define MINT		RGB  0.8  1    0.8
#define LTBLUE		RGB  0.5  0.5  1
#define LTYELLOW	RGB  1    1    0.5
#define ORANGE		RGB  1    0.5  0
#define BROWN		#8C6238
