#define error		     HSV 20 0.5 0.5

#define well		     #101010
#define shadow           #101010

#define selection_hilite #404040
#define selection_shadow #202020

#define list_a		     #181818
#define list_b		     #101010

#define blue             #3047ba
#define green		     #00ff00
#define red			     #ff0000
#define white            #ffffff

#define arrow		     #909090
#define text             #909090
#define pressed_arrow    #505050

#define black            #000000
#define dark             #202020
#define darker           #202020
#define mid              #404040
#define lite             #a0a0a0
