#define error   HSV 20 0.5 0.5
#define blue    #3047ba
#define green   #00ff00
#define red	    #ff0000



#define blue0   #000036
#define blue1   #114BD3
#define blue2   #116CD3
#define blue3   #03022B

#define brown1  #161414

#define grey0   #000000
#define grey1   #101010
#define grey2   #151515
#define grey3   #181818
#define grey4   #202020
#define grey5   #404040
#define grey6   #505050
#define grey7   #909090
#define grey8   #a0a0a0
#define grey9   #ffffff

#define red9    #ff0000

#define yellow1 #6A5148
