#define _100		HSV 20 1 0.8

#define bg_dim		HSV 20 0.15 0.06
#define bg			RGB 0.085 0.085 0.085
#define bg_lite 	HSV 20 0.1 0.15
#define bg_liter	HSV 20 0.1 0.2

#define bg_1		HSV 20 0.05 0.2
#define bg_2		HSV 10 0.15 0.15
#define bg_3		HSV 20 0.15 0.2

#define _2			HSV 20 0.15 0.15
#define _3			HSV 20 0.15 0.2
#define _4			HSV 20 0.15 0.25
#define _5			HSV 20 0.15 0.3
#define _6			HSV 15 0.15 0.5
#define _7			HSV 20 0.15 0.7
#define _8			HSV 20 0.15 0.8
#define _9			HSV 20 0.15 0.9

#define blu			HSV 200 0.5 0.5

#define err			HSV 20 0.5 0.5

#define rose_2		HSL 17.85 0.93 0.15
#define rose_3		HSL 17.85 0.4 0.3
#define rose_4		HSL 17.85 0.5 0.4
#define rose_5		HSL 20 0.5 0.65

#define fg_dimmer	HSL 20 0.2 0.3
#define fg_dim		HSL 20 0.3 0.5
#define fg			HSL 20 0.5 0.7
#define fg_lite		HSL 20 0.5 0.65

// define DRKBASE		RGB 1 0 0
#define WELL		RGB 1 0 0
#define LISTA		_2
#define LISTB		_3

#define unk			RGB 1 0 0
#define unk_b		RGB 0 1 0

#define GREY(g)		_8
#define BLACK		RGB 0 0 0
#define WHITE		RGB 1 1 1
#define ARROW		RGB 0.5 0.5 0.5
#define GREEN		HSV 0.25 0.41 0.23
